spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/keycloak-spring-boot-angular-integration
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 7071

jwt:
  auth:
    converter:
      resource-id: keycloak-springboot-angular-backend
      principle-attribute: preferred_username
